version: '1.0'

services:
  server:
    build: ./server
    volumes:
      - ./server:/server
    environment:
      - SCOREBOARD_URL=172.28.13.183:8000
      - SYSTEM_TOKEN=934310005a1447b8bd52d9dcbd5c405a
      - SUBMIT_FLAG_LIMIT=50
      - SUBMIT_PERIOD=50
      - FLAG_LIFETIME=1500
      - TICK_PERIOD=300
    ports:
      - 5000:5000